#Crea un archivo docker-compose.yml para desplegar los servicios de mysql y phpmyadmin, pero
 #   deberá utilizar la última versión de la imagen de mysql.
  #Nota: Es posible que cuando quiera conectarse desde phpmyadmin a mysql obtenga errores
   # similares a estos
  #• mysqli_real_connect(): The server requested authentication method unknown to the client
  #  [caching_sha2_password]
  #• mysqli_real_connect(): (HY000/2054): The server requested authentication method
   # unknown to the client
    #Para solucionar este problema deberá sobrescribir el comando con el que se inicia el
    #servicio de mysql para indicar que el plugin de autenticación por defecto es de tipo
    #mysql_native_password.
    #En la sección de definición del servicio de mysql deberá añadir la opción command con el
    #siguiente valor.

  #...
  #mysql:
  #image: mysql
  #command: --default-authentication-plugin=mysql_native_password
   # ...
version: '3'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepassword
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data: